/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Oscar
 */
public class FrmCli extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmArt
     */
    public FrmCli() {
        initComponents();
    }

    public JButton getBtnAddCliente() {
        return btnAddCliente;
    }

    public void setBtnAddCliente(JButton btnAddCliente) {
        this.btnAddCliente = btnAddCliente;
    }

    public JButton getBtnCancelCliente() {
        return btnCancelCliente;
    }

    public void setBtnCancelCliente(JButton btnCancelCliente) {
        this.btnCancelCliente = btnCancelCliente;
    }

    public JComboBox<String> getCbCliente() {
        return cbCliente;
    }

    public void setCbCliente(JComboBox<String> cbCliente) {
        this.cbCliente = cbCliente;
    }

    public JTextArea getTxaCliente() {
        return txaCliente;
    }

    public void setTxaCliente(JTextArea txaCliente) {
        this.txaCliente = txaCliente;
    }

    public JTextField getTxtIdCliente() {
        return txtIdCliente;
    }

    public void setTxtIdCliente(JTextField txtIdCliente) {
        this.txtIdCliente = txtIdCliente;
    }

    public JTextField getTxtNomCliente() {
        return txtNomCliente;
    }

    public void setTxtNomCliente(JTextField txtNomCliente) {
        this.txtNomCliente = txtNomCliente;
    }

    public JTextField getTxtPagoCliente() {
        return txtPagoCliente;
    }

    public void setTxtPagoCliente(JTextField txtPagoCliente) {
        this.txtPagoCliente = txtPagoCliente;
    }

    public JTextField getTxtTelCliente() {
        return txtTelCliente;
    }

    public void setTxtTelCliente(JTextField txtTelCliente) {
        this.txtTelCliente = txtTelCliente;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cbCliente = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        txtIdCliente = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        txtNomCliente = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        txtTelCliente = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        txtPagoCliente = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        btnAddCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCancelCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCliente = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Registro: Cliente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jPanel16.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Edad");
        jPanel16.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel16);

        jPanel17.setLayout(new java.awt.BorderLayout());
        jPanel17.add(jPanel4, java.awt.BorderLayout.PAGE_START);
        jPanel17.add(jPanel5, java.awt.BorderLayout.PAGE_END);
        jPanel17.add(jPanel6, java.awt.BorderLayout.LINE_START);

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adulto", "Niño" }));
        jPanel17.add(cbCliente, java.awt.BorderLayout.CENTER);
        jPanel17.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel17);

        jPanel18.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel7.setText("Identificacion: ");
        jPanel18.add(jLabel7, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel18);

        jPanel19.setLayout(new java.awt.BorderLayout());
        jPanel19.add(txtIdCliente, java.awt.BorderLayout.CENTER);
        jPanel19.add(jPanel8, java.awt.BorderLayout.PAGE_START);
        jPanel19.add(jPanel9, java.awt.BorderLayout.PAGE_END);
        jPanel19.add(jPanel10, java.awt.BorderLayout.LINE_START);
        jPanel19.add(jPanel11, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel8.setText("Nombre: ");
        jPanel20.add(jLabel8, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel20);

        jPanel21.setLayout(new java.awt.BorderLayout());
        jPanel21.add(txtNomCliente, java.awt.BorderLayout.CENTER);
        jPanel21.add(jPanel12, java.awt.BorderLayout.PAGE_START);
        jPanel21.add(jPanel13, java.awt.BorderLayout.PAGE_END);
        jPanel21.add(jPanel14, java.awt.BorderLayout.LINE_START);
        jPanel21.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel21);

        jPanel22.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel9.setText("Telefono: ");
        jPanel22.add(jLabel9, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel22);

        jPanel23.setLayout(new java.awt.BorderLayout());

        txtTelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelClienteActionPerformed(evt);
            }
        });
        jPanel23.add(txtTelCliente, java.awt.BorderLayout.CENTER);
        jPanel23.add(jPanel24, java.awt.BorderLayout.PAGE_START);
        jPanel23.add(jPanel28, java.awt.BorderLayout.PAGE_END);
        jPanel23.add(jPanel29, java.awt.BorderLayout.LINE_START);
        jPanel23.add(jPanel30, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel23);

        jPanel25.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel10.setText("Valor a pagar:");
        jPanel25.add(jLabel10, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel25);

        jPanel26.setLayout(new java.awt.BorderLayout());

        txtPagoCliente.setEditable(false);
        jPanel26.add(txtPagoCliente, java.awt.BorderLayout.CENTER);
        jPanel26.add(jPanel31, java.awt.BorderLayout.PAGE_START);
        jPanel26.add(jPanel32, java.awt.BorderLayout.PAGE_END);
        jPanel26.add(jPanel33, java.awt.BorderLayout.LINE_START);
        jPanel26.add(jPanel34, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridBagLayout());

        btnAddCliente.setText("Agregar cliente...");
        jPanel27.add(btnAddCliente, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel27);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnCancelCliente.setText("Cancelar");
        jPanel2.add(btnCancelCliente, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        txaCliente.setColumns(20);
        txaCliente.setRows(5);
        jScrollPane1.setViewportView(txaCliente);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCliente;
    private javax.swing.JButton btnCancelCliente;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaCliente;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNomCliente;
    private javax.swing.JTextField txtPagoCliente;
    private javax.swing.JTextField txtTelCliente;
    // End of variables declaration//GEN-END:variables
}
