/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar
 */
public class frmListaCli extends javax.swing.JInternalFrame {
    
    private DefaultTableModel tblCli;

    /**
     * Creates new form frmListaCli
     */
    public frmListaCli() {
        initComponents();
        tblCli = (DefaultTableModel) tblListClie.getModel();
    }
    

    public JButton getBtnListCliCan() {
        return btnListCliCan;
    }

    public void setBtnListCliCan(JButton btnListCliCan) {
        this.btnListCliCan = btnListCliCan;
    }

    public DefaultTableModel getTblCli() {
        return tblCli;
    }

    public void setTblCli(DefaultTableModel tblCli) {
        this.tblCli = tblCli;
    }

  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListClie = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnListCliCan = new javax.swing.JButton();

        tblListClie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Telefono", "Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListClie);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btnListCliCan.setText("Cerrar");
        jPanel2.add(btnListCliCan);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListCliCan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListClie;
    // End of variables declaration//GEN-END:variables
}
