/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar
 */
public class FrmListArt extends javax.swing.JInternalFrame {
    
     private DefaultTableModel tblArt;

    /**
     * Creates new form FrmListArt
     */
    public FrmListArt() {
        initComponents();
        tblArt = (DefaultTableModel) tblListArt.getModel();
    }

    public DefaultTableModel getTblArt() {
        return tblArt;
    }

    public void setTblArt(DefaultTableModel tblArt) {
        this.tblArt = tblArt;
    }

    public JButton getBtnListArtCerrar() {
        return btnListArtCerrar;
    }

    public void setBtnListArtCerrar(JButton btnListArtCerrar) {
        this.btnListArtCerrar = btnListArtCerrar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListArt = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnListArtCerrar = new javax.swing.JButton();

        tblListArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Telefono", "Direccion", "Ciudad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListArt);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btnListArtCerrar.setText("Cerrar");
        jPanel2.add(btnListArtCerrar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListArtCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListArt;
    // End of variables declaration//GEN-END:variables
}
