/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Oscar
 */
public class FrmObra extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmObra
     */
    public FrmObra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cbTipoObra = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        cbOpcVenta = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        txtCodObra = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        txtNomObra = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        cbArtistaObra = new javax.swing.JComboBox<>();
        jPanel25 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        txtPrecioObra = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        btnAddObra = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnCancelObra = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaObra = new javax.swing.JTextArea();
        jPanel27 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        btnAddArtObra = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Tipo de obra");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3);

        jLabel2.setText("Esta a la venta?");
        jPanel4.add(jLabel2);

        jPanel1.add(jPanel4);

        cbTipoObra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pintura", "Escultura", "Dibujo a lapiz" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(cbTipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(cbTipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        cbOpcVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(cbOpcVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(cbOpcVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new java.awt.GridLayout(5, 2));

        jPanel18.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel7.setText("Codigo:");
        jPanel18.add(jLabel7, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel18);

        jPanel19.setLayout(new java.awt.BorderLayout());
        jPanel19.add(txtCodObra, java.awt.BorderLayout.CENTER);
        jPanel19.add(jPanel8, java.awt.BorderLayout.PAGE_START);
        jPanel19.add(jPanel9, java.awt.BorderLayout.PAGE_END);
        jPanel19.add(jPanel10, java.awt.BorderLayout.LINE_START);
        jPanel19.add(jPanel11, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel8.setText("Nombre: ");
        jPanel20.add(jLabel8, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel20);

        jPanel21.setLayout(new java.awt.BorderLayout());
        jPanel21.add(txtNomObra, java.awt.BorderLayout.CENTER);
        jPanel21.add(jPanel12, java.awt.BorderLayout.PAGE_START);
        jPanel21.add(jPanel13, java.awt.BorderLayout.PAGE_END);
        jPanel21.add(jPanel14, java.awt.BorderLayout.LINE_START);
        jPanel21.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel21);

        jPanel22.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel9.setText("Artista:");
        jPanel22.add(jLabel9, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel22);

        jPanel23.setLayout(new java.awt.BorderLayout());
        jPanel23.add(jPanel24, java.awt.BorderLayout.PAGE_START);
        jPanel23.add(jPanel28, java.awt.BorderLayout.PAGE_END);
        jPanel23.add(jPanel29, java.awt.BorderLayout.LINE_START);
        jPanel23.add(jPanel30, java.awt.BorderLayout.LINE_END);

        cbArtistaObra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel23.add(cbArtistaObra, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel23);

        jPanel25.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel10.setText("Precio: ");
        jPanel25.add(jLabel10, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel25);

        jPanel26.setLayout(new java.awt.BorderLayout());
        jPanel26.add(txtPrecioObra, java.awt.BorderLayout.CENTER);
        jPanel26.add(jPanel31, java.awt.BorderLayout.PAGE_START);
        jPanel26.add(jPanel32, java.awt.BorderLayout.PAGE_END);
        jPanel26.add(jPanel33, java.awt.BorderLayout.LINE_START);
        jPanel26.add(jPanel34, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel26);

        jPanel16.setLayout(new java.awt.GridBagLayout());

        btnAddObra.setText("Agregar obra...");
        jPanel16.add(btnAddObra, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel16);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        btnCancelObra.setText("Cancelar");
        jPanel7.add(btnCancelObra, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel36.setLayout(new java.awt.BorderLayout());

        txaObra.setColumns(20);
        txaObra.setRows(5);
        jScrollPane1.setViewportView(txaObra);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel36.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        jPanel27.setLayout(new java.awt.GridLayout(1, 2));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel3.setText("No encuentra el artista?");
        jPanel37.add(jLabel3);

        jPanel27.add(jPanel37);

        jPanel40.setLayout(new java.awt.GridBagLayout());

        btnAddArtObra.setText("Agregar artista...");
        btnAddArtObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArtObraActionPerformed(evt);
            }
        });
        jPanel40.add(btnAddArtObra, new java.awt.GridBagConstraints());

        jPanel27.add(jPanel40);

        jPanel36.add(jPanel27, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel36, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddArtObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArtObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddArtObraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArtObra;
    private javax.swing.JButton btnAddObra;
    private javax.swing.JButton btnCancelObra;
    private javax.swing.JComboBox<String> cbArtistaObra;
    private javax.swing.JComboBox<String> cbOpcVenta;
    private javax.swing.JComboBox<String> cbTipoObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaObra;
    private javax.swing.JTextField txtCodObra;
    private javax.swing.JTextField txtNomObra;
    private javax.swing.JTextField txtPrecioObra;
    // End of variables declaration//GEN-END:variables
}
