/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author Oscar
 */
public class FrmPpal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPpal
     */
    public FrmPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuArtista = new javax.swing.JMenuItem();
        mnuCliente = new javax.swing.JMenuItem();
        mnuObra = new javax.swing.JMenuItem();
        mnuVenta = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnuTabArtistas = new javax.swing.JMenuItem();
        mnuTabClientes = new javax.swing.JMenuItem();
        mnuTabObras = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        escritorio.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenu3.setText("Nuevo");

        mnuArtista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuArtista.setText("Artista");
        jMenu3.add(mnuArtista);

        mnuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuCliente.setText("Cliente");
        jMenu3.add(mnuCliente);

        mnuObra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnuObra.setText("Obra");
        jMenu3.add(mnuObra);

        jMenu1.add(jMenu3);

        mnuVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        mnuVenta.setText("Venta");
        jMenu1.add(mnuVenta);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Salir");
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver");

        jMenu4.setText("Tabla");

        mnuTabArtistas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        mnuTabArtistas.setText("Artistas");
        jMenu4.add(mnuTabArtistas);

        mnuTabClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mnuTabClientes.setText("Clientes");
        jMenu4.add(mnuTabClientes);

        mnuTabObras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK));
        mnuTabObras.setText("Obras");
        jMenu4.add(mnuTabObras);

        jMenu2.add(jMenu4);

        mnuReporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuReporte.setText("Reporte de ventas");
        jMenu2.add(mnuReporte);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuArtista;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuObra;
    private javax.swing.JMenuItem mnuReporte;
    private javax.swing.JMenuItem mnuTabArtistas;
    private javax.swing.JMenuItem mnuTabClientes;
    private javax.swing.JMenuItem mnuTabObras;
    private javax.swing.JMenuItem mnuVenta;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public JMenuItem getMnuArtista() {
        return mnuArtista;
    }

    public JMenuItem getMnuCliente() {
        return mnuCliente;
    }

    public JMenuItem getMnuExit() {
        return mnuExit;
    }

    public JMenuItem getMnuObra() {
        return mnuObra;
    }

    public JMenuItem getMnuReporte() {
        return mnuReporte;
    }

    public JMenuItem getMnuTabArtistas() {
        return mnuTabArtistas;
    }

    public JMenuItem getMnuTabClientes() {
        return mnuTabClientes;
    }

    public JMenuItem getMnuTabObras() {
        return mnuTabObras;
    }

    public JMenuItem getMnuVenta() {
        return mnuVenta;
    }



}