/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Oscar
 */
public class FrmVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVenta
     */
    public FrmVenta() {
        initComponents();
    }

    public JButton getBtnCancelVenta() {
        return btnCancelVenta;
    }

    public void setBtnCancelVenta(JButton btnCancelVenta) {
        this.btnCancelVenta = btnCancelVenta;
    }

    public JButton getBtnRegVenta() {
        return btnRegVenta;
    }

    public void setBtnRegVenta(JButton btnRegVenta) {
        this.btnRegVenta = btnRegVenta;
    }

    public JComboBox<String> getCbCliVenta() {
        return cbCliVenta;
    }

    public void setCbCliVenta(JComboBox<String> cbCliVenta) {
        this.cbCliVenta = cbCliVenta;
    }

    public JComboBox<String> getCbNombreVenta() {
        return cbNombreVenta;
    }

    public void setCbNombreVenta(JComboBox<String> cbNombreVenta) {
        this.cbNombreVenta = cbNombreVenta;
    }

    public JComboBox<String> getCbTipoVenta() {
        return cbTipoVenta;
    }

    public void setCbTipoVenta(JComboBox<String> cbTipoVenta) {
        this.cbTipoVenta = cbTipoVenta;
    }

    public JTextArea getTxaVenta() {
        return txaVenta;
    }

    public void setTxaVenta(JTextArea txaVenta) {
        this.txaVenta = txaVenta;
    }

    public JTextField getTxtImpVenta() {
        return txtImpVenta;
    }

    public void setTxtImpVenta(JTextField txtImpVenta) {
        this.txtImpVenta = txtImpVenta;
    }

    public JTextField getTxtPrecioVenta() {
        return txtPrecioVenta;
    }

    public void setTxtPrecioVenta(JTextField txtPrecioVenta) {
        this.txtPrecioVenta = txtPrecioVenta;
    }

    public JTextField getTxtTotalVenta() {
        return txtTotalVenta;
    }

    public void setTxtTotalVenta(JTextField txtTotalVenta) {
        this.txtTotalVenta = txtTotalVenta;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaVenta = new javax.swing.JTextArea();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbTipoVenta = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cbNombreVenta = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        cbCliVenta = new javax.swing.JComboBox<>();
        jPanel35 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        txtPrecioVenta = new javax.swing.JTextField();
        jPanel55 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        txtImpVenta = new javax.swing.JTextField();
        jPanel57 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        txtTotalVenta = new javax.swing.JTextField();
        jPanel59 = new javax.swing.JPanel();
        btnRegVenta = new javax.swing.JButton();
        jPanel60 = new javax.swing.JPanel();
        btnCancelVenta = new javax.swing.JButton();

        txaVenta.setColumns(20);
        txaVenta.setRows(5);
        jScrollPane1.setViewportView(txaVenta);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel17, java.awt.BorderLayout.PAGE_END);

        jPanel18.setLayout(new java.awt.GridLayout(7, 2));

        jPanel19.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de obra a vender");
        jPanel19.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel18.add(jPanel19);

        jPanel20.setLayout(new java.awt.BorderLayout());
        jPanel20.add(jPanel1, java.awt.BorderLayout.PAGE_START);
        jPanel20.add(jPanel2, java.awt.BorderLayout.PAGE_END);
        jPanel20.add(jPanel3, java.awt.BorderLayout.LINE_START);
        jPanel20.add(jPanel4, java.awt.BorderLayout.LINE_END);

        cbTipoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pintura", "Escultura", "Obra a lapiz" }));
        cbTipoVenta.setSelectedIndex(-1);
        jPanel20.add(cbTipoVenta, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel20);

        jPanel21.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel2.setText("Nombre de obra");
        jPanel21.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel18.add(jPanel21);

        jPanel22.setLayout(new java.awt.BorderLayout());
        jPanel22.add(jPanel5, java.awt.BorderLayout.PAGE_START);
        jPanel22.add(jPanel6, java.awt.BorderLayout.PAGE_END);
        jPanel22.add(jPanel7, java.awt.BorderLayout.LINE_START);
        jPanel22.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel22.add(cbNombreVenta, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel22);

        jPanel23.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel3.setText("Cliente");
        jPanel23.add(jLabel3, new java.awt.GridBagConstraints());

        jPanel18.add(jPanel23);

        jPanel24.setLayout(new java.awt.BorderLayout());
        jPanel24.add(jPanel9, java.awt.BorderLayout.LINE_START);
        jPanel24.add(jPanel10, java.awt.BorderLayout.LINE_END);
        jPanel24.add(jPanel11, java.awt.BorderLayout.PAGE_END);
        jPanel24.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel24.add(cbCliVenta, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel24);

        jPanel35.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel4.setText("Precio obra");
        jPanel35.add(jLabel4, new java.awt.GridBagConstraints());

        jPanel18.add(jPanel35);

        jPanel54.setLayout(new java.awt.BorderLayout());
        jPanel54.add(jPanel13, java.awt.BorderLayout.PAGE_START);
        jPanel54.add(jPanel14, java.awt.BorderLayout.LINE_START);
        jPanel54.add(jPanel15, java.awt.BorderLayout.LINE_END);
        jPanel54.add(jPanel16, java.awt.BorderLayout.PAGE_END);

        txtPrecioVenta.setEditable(false);
        jPanel54.add(txtPrecioVenta, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel54);

        jPanel55.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel5.setText("Impuesto");
        jPanel55.add(jLabel5, new java.awt.GridBagConstraints());

        jPanel18.add(jPanel55);

        jPanel56.setLayout(new java.awt.BorderLayout());
        jPanel56.add(jPanel25, java.awt.BorderLayout.PAGE_START);
        jPanel56.add(jPanel26, java.awt.BorderLayout.LINE_START);
        jPanel56.add(jPanel27, java.awt.BorderLayout.LINE_END);
        jPanel56.add(jPanel28, java.awt.BorderLayout.PAGE_END);

        txtImpVenta.setEditable(false);
        txtImpVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpVentaActionPerformed(evt);
            }
        });
        jPanel56.add(txtImpVenta, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel56);

        jPanel57.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel6.setText("Total a pagar");
        jPanel57.add(jLabel6, new java.awt.GridBagConstraints());

        jPanel18.add(jPanel57);

        jPanel58.setLayout(new java.awt.BorderLayout());
        jPanel58.add(jPanel29, java.awt.BorderLayout.PAGE_START);
        jPanel58.add(jPanel30, java.awt.BorderLayout.LINE_START);
        jPanel58.add(jPanel31, java.awt.BorderLayout.LINE_END);
        jPanel58.add(jPanel32, java.awt.BorderLayout.PAGE_END);

        txtTotalVenta.setEditable(false);
        jPanel58.add(txtTotalVenta, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel58);

        jPanel59.setLayout(new java.awt.GridBagLayout());

        btnRegVenta.setText("Registrar venta...");
        jPanel59.add(btnRegVenta, new java.awt.GridBagConstraints());

        jPanel18.add(jPanel59);

        jPanel60.setLayout(new java.awt.GridBagLayout());

        btnCancelVenta.setText("Cancelar");
        jPanel60.add(btnCancelVenta, new java.awt.GridBagConstraints());

        jPanel18.add(jPanel60);

        getContentPane().add(jPanel18, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImpVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelVenta;
    private javax.swing.JButton btnRegVenta;
    private javax.swing.JComboBox<String> cbCliVenta;
    private javax.swing.JComboBox<String> cbNombreVenta;
    private javax.swing.JComboBox<String> cbTipoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaVenta;
    private javax.swing.JTextField txtImpVenta;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
